In [1]:

# imports
import os
import sys
import types
import json
import base64

# figure size/format
fig_width = 7
fig_height = 5
fig_format = 'retina'
fig_dpi = 96
interactivity = ''
is_shiny = False
is_dashboard = False
plotly_connected = True

# matplotlib defaults / format
try:
  import matplotlib.pyplot as plt
  plt.rcParams['figure.figsize'] = (fig_width, fig_height)
  plt.rcParams['figure.dpi'] = fig_dpi
  plt.rcParams['savefig.dpi'] = "figure"
  from IPython.display import set_matplotlib_formats
  set_matplotlib_formats(fig_format)
except Exception:
  pass

# plotly use connected mode
try:
  import plotly.io as pio
  if plotly_connected:
    pio.renderers.default = "notebook_connected"
  else:
    pio.renderers.default = "notebook"
  for template in pio.templates.keys():
    pio.templates[template].layout.margin = dict(t=30,r=0,b=0,l=0)
except Exception:
  pass

# disable itables paging for dashboards
if is_dashboard:
  try:
    from itables import options
    options.dom = 'fiBrtlp'
    options.maxBytes = 1024 * 1024
    options.language = dict(info = "Showing _TOTAL_ entries")
    options.classes = "display nowrap compact"
    options.paging = False
    options.searching = True
    options.ordering = True
    options.info = True
    options.lengthChange = False
    options.autoWidth = False
    options.responsive = True
    options.keys = True
    options.buttons = []
  except Exception:
    pass
  
  try:
    import altair as alt
    # By default, dashboards will have container sized
    # vega visualizations which allows them to flow reasonably
    theme_sentinel = '_quarto-dashboard-internal'
    def make_theme(name):
        nonTheme = alt.themes._plugins[name]    
        def patch_theme(*args, **kwargs):
            existingTheme = nonTheme()
            if 'height' not in existingTheme:
              existingTheme['height'] = 'container'
            if 'width' not in existingTheme:
              existingTheme['width'] = 'container'

            if 'config' not in existingTheme:
              existingTheme['config'] = dict()
            
            # Configure the default font sizes
            title_font_size = 15
            header_font_size = 13
            axis_font_size = 12
            legend_font_size = 12
            mark_font_size = 12
            tooltip = False

            config = existingTheme['config']

            # The Axis
            if 'axis' not in config:
              config['axis'] = dict()
            axis = config['axis']
            if 'labelFontSize' not in axis:
              axis['labelFontSize'] = axis_font_size
            if 'titleFontSize' not in axis:
              axis['titleFontSize'] = axis_font_size  

            # The legend
            if 'legend' not in config:
              config['legend'] = dict()
            legend = config['legend']
            if 'labelFontSize' not in legend:
              legend['labelFontSize'] = legend_font_size
            if 'titleFontSize' not in legend:
              legend['titleFontSize'] = legend_font_size  

            # The header
            if 'header' not in config:
              config['header'] = dict()
            header = config['header']
            if 'labelFontSize' not in header:
              header['labelFontSize'] = header_font_size
            if 'titleFontSize' not in header:
              header['titleFontSize'] = header_font_size    

            # Title
            if 'title' not in config:
              config['title'] = dict()
            title = config['title']
            if 'fontSize' not in title:
              title['fontSize'] = title_font_size

            # Marks
            if 'mark' not in config:
              config['mark'] = dict()
            mark = config['mark']
            if 'fontSize' not in mark:
              mark['fontSize'] = mark_font_size

            # Mark tooltips
            if tooltip and 'tooltip' not in mark:
              mark['tooltip'] = dict(content="encoding")

            return existingTheme
            
        return patch_theme

    # We can only do this once per session
    if theme_sentinel not in alt.themes.names():
      for name in alt.themes.names():
        alt.themes.register(name, make_theme(name))
      
      # register a sentinel theme so we only do this once
      alt.themes.register(theme_sentinel, make_theme('default'))
      alt.themes.enable('default')

  except Exception:
    pass

# enable pandas latex repr when targeting pdfs
try:
  import pandas as pd
  if fig_format == 'pdf':
    pd.set_option('display.latex.repr', True)
except Exception:
  pass

# interactivity
if interactivity:
  from IPython.core.interactiveshell import InteractiveShell
  InteractiveShell.ast_node_interactivity = interactivity

# NOTE: the kernel_deps code is repeated in the cleanup.py file
# (we can't easily share this code b/c of the way it is run).
# If you edit this code also edit the same code in cleanup.py!

# output kernel dependencies
kernel_deps = dict()
for module in list(sys.modules.values()):
  # Some modules play games with sys.modules (e.g. email/__init__.py
  # in the standard library), and occasionally this can cause strange
  # failures in getattr.  Just ignore anything that's not an ordinary
  # module.
  if not isinstance(module, types.ModuleType):
    continue
  path = getattr(module, "__file__", None)
  if not path:
    continue
  if path.endswith(".pyc") or path.endswith(".pyo"):
    path = path[:-1]
  if not os.path.exists(path):
    continue
  kernel_deps[path] = os.stat(path).st_mtime
print(json.dumps(kernel_deps))

# set run_path if requested
run_path = 'L1VzZXJzL2Z0MTQ5NjgvUmVwb3MvaW50cm8tY29kaW5nLWRhdGEtYW5hbHlzaXMvcXVhcnRvLzA4'
if run_path:
  # hex-decode the path
  run_path = base64.b64decode(run_path.encode("utf-8")).decode("utf-8")
  os.chdir(run_path)

# reset state
%reset

# shiny
# Checking for shiny by using False directly because we're after the %reset. We don't want
# to set a variable that stays in global scope.
if False:
  try:
    import htmltools as _htmltools
    import ast as _ast

    _htmltools.html_dependency_render_mode = "json"

    # This decorator will be added to all function definitions
    def _display_if_has_repr_html(x):
      try:
        # IPython 7.14 preferred import
        from IPython.display import display, HTML
      except:
        from IPython.core.display import display, HTML

      if hasattr(x, '_repr_html_'):
        display(HTML(x._repr_html_()))
      return x

    # ideally we would undo the call to ast_transformers.append
    # at the end of this block whenver an error occurs, we do 
    # this for now as it will only be a problem if the user 
    # switches from shiny to not-shiny mode (and even then likely
    # won't matter)
    import builtins
    builtins._display_if_has_repr_html = _display_if_has_repr_html

    class _FunctionDefReprHtml(_ast.NodeTransformer):
      def visit_FunctionDef(self, node):
        node.decorator_list.insert(
          0,
          _ast.Name(id="_display_if_has_repr_html", ctx=_ast.Load())
        )
        return node

      def visit_AsyncFunctionDef(self, node):
        node.decorator_list.insert(
          0,
          _ast.Name(id="_display_if_has_repr_html", ctx=_ast.Load())
        )
        return node

    ip = get_ipython()
    ip.ast_transformers.append(_FunctionDefReprHtml())

  except:
    pass

def ojs_define(**kwargs):
  import json
  try:
    # IPython 7.14 preferred import
    from IPython.display import display, HTML
  except:
    from IPython.core.display import display, HTML

  # do some minor magic for convenience when handling pandas
  # dataframes
  def convert(v):
    try:
      import pandas as pd
    except ModuleNotFoundError: # don't do the magic when pandas is not available
      return v
    if type(v) == pd.Series:
      v = pd.DataFrame(v)
    if type(v) == pd.DataFrame:
      j = json.loads(v.T.to_json(orient='split'))
      return dict((k,v) for (k,v) in zip(j["index"], j["data"]))
    else:
      return v

  v = dict(contents=list(dict(name=key, value=convert(value)) for (key, value) in kwargs.items()))
  display(HTML('<script type="ojs-define">' + json.dumps(v) + '</script>'), metadata=dict(ojs_define = True))
globals()["ojs_define"] = ojs_define
globals()["__spec__"] = None

{"/Users/ft14968/.pyenv/versions/3.11.1/lib/python3.11/importlib/_bootstrap.py": 1716061061.963526, "/Users/ft14968/.pyenv/versions/3.11.1/lib/python3.11/importlib/_bootstrap_external.py": 1716061061.9664707, "/Users/ft14968/.pyenv/versions/3.11.1/lib/python3.11/zipimport.py": 1716061059.8541, "/Users/ft14968/.pyenv/versions/3.11.1/lib/python3.11/codecs.py": 1716061059.3098388, "/Users/ft14968/.pyenv/versions/3.11.1/lib/python3.11/encodings/aliases.py": 1716061060.5232508, "/Users/ft14968/.pyenv/versions/3.11.1/lib/python3.11/encodings/__init__.py": 1716061060.520605, "/Users/ft14968/.pyenv/versions/3.11.1/lib/python3.11/encodings/utf_8.py": 1716061061.3768034, "/Users/ft14968/.pyenv/versions/3.11.1/lib/python3.11/abc.py": 1716061059.2254992, "/Users/ft14968/.pyenv/versions/3.11.1/lib/python3.11/io.py": 1716061059.4591994, "/Users/ft14968/.pyenv/versions/3.11.1/lib/python3.11/stat.py": 1716061059.7052634, "/Users/ft14968/.pyenv/versions/3.11.1/lib/python3.11/_collections_abc.py": 17160

In [2]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print("Array:", arr)
print("Element at index 1:", arr[1])

Array: [10 20 30 40 50]
Element at index 1: 20


In [3]:
print("Slice from index 1 to 3:", arr[1:4])

Slice from index 1 to 3: [20 30 40]


In [4]:
# Step size: select every other element
print("Every other element:", arr[::2])

# Negative indices: last three elements
print("Last three elements:", arr[-3:])

# Reverse slicing: reverse the array
print("Reversed array:", arr[::-1])

# Selecting all elements
print("All elements:", arr[:])

Every other element: [10 30 50]
Last three elements: [30 40 50]
Reversed array: [50 40 30 20 10]
All elements: [10 20 30 40 50]


In [5]:
# Demonstrating that slicing creates a view, not a copy
slice_view = arr[2:5]
print("Original array before modification:", arr)
slice_view[0] = 99  # Modify the view
print("Modified slice_view:", slice_view)
print("Original array after modification:", arr)  # arr is also changed

Original array before modification: [10 20 30 40 50]
Modified slice_view: [99 40 50]
Original array after modification: [10 20 99 40 50]


In [6]:
# Creating an independent copy of a slice
example_slice = slice(1, 4, 2)
print("Using slice(1, 4, 2) on arr:", arr[example_slice])

Using slice(1, 4, 2) on arr: [20 40]


In [7]:
# Creating an independent copy of a slice
arr_copy = arr[2:5].copy()
arr_copy[0] = 100  # Modify the copy
print("arr_copy:", arr_copy)
print("Original arr:", arr)  # arr remains unchanged

arr_copy: [100  40  50]
Original arr: [10 20 99 40 50]


In [8]:
arr = np.array([1, 2, 3, 4, 5, 6])
threshold = 3
bool_mask = arr > threshold
print("Original array:", arr)
print(f"Boolean mask for threshold {threshold}:", bool_mask)
print("Filtered values:", arr[bool_mask])

Original array: [1 2 3 4 5 6]
Boolean mask for threshold 3: [False False False  True  True  True]
Filtered values: [4 5 6]


In [9]:
np.where(arr > threshold)

(array([3, 4, 5]),)

In [10]:
np.where(arr > threshold)[0]

array([3, 4, 5])

In [11]:
a  = np.array([1, 2, 3, 4, 5])
b = np.array([-1,-2, -3, - 4, -5])
c = np.array([10, 20, 30, 40, 50])

result = np.where(a > 2, x, y)
print(result)

NameError: name 'x' is not defined

In [12]:
print("np.arange(0, 10, 2):", np.arange(0, 10, 2))
print("np.linspace(0, 1, 5):", np.linspace(0, 1, 5))

np.arange(0, 10, 2): [0 2 4 6 8]
np.linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]


In [13]:
# integers
np.arange(0, 10, 2)  # Creates an array with values from 0 to 10 with a step of 2

array([0, 2, 4, 6, 8])

In [14]:
# floating-point numbers
np.arange(0.0, 1.0, 0.2)  # Creates an array with values from 0.0 to 1.0 with a step of 0.2

array([0. , 0.2, 0.4, 0.6, 0.8])

In [15]:
# complex numbers, by using the data type specifier `dtype=complex`
np.arange(0, 10, 2, dtype=complex)  # Creates an array with complex numbers from 0 to 10 with a step of 2

array([0.+0.j, 2.+0.j, 4.+0.j, 6.+0.j, 8.+0.j])

In [16]:
# Examples using filled array generation functions

# Create a 1D array of zeros with the same shape as arr
zeros_arr = np.zeros_like(arr)
print("Zeros array:", zeros_arr)

# Create a 1D array of ones with the same shape as arr
ones_arr = np.ones_like(arr)
print("Ones array:", ones_arr)

# Create a 1D array filled with the value 7, same shape as arr
full_arr = np.full_like(arr, 7)
print("Full array (filled with 7):", full_arr)

# Create an uninitialized array (values may be random, or zeros)
empty_2d = np.empty(5)
print("An empty array:\n", empty_2d)

Zeros array: [0 0 0 0 0 0]
Ones array: [1 1 1 1 1 1]
Full array (filled with 7): [7 7 7 7 7 7]
An empty array:
 [0. 0. 0. 0. 0.]


In [17]:
def lcg(seed, a=1664525, c=1013904223, m=2**32, size=10):
    nums = []
    x = seed
    for _ in range(size):
        x = (a * x + c) % m
        nums.append(x)
    return nums

In [18]:
# Example usage:
lcg_sequence = lcg(seed=42, size=5)
print("LCG sequence:", lcg_sequence)

LCG sequence: [1083814273, 378494188, 2479403867, 955863294, 1613448261]


In [19]:
# Example of LCG with a short period by choosing small modulus
short_period_seq = lcg(seed=1,  a=5, c=3, m=16, size=20)
print("LCG sequence with short period:", short_period_seq)

LCG sequence with short period: [8, 11, 10, 5, 12, 15, 14, 9, 0, 3, 2, 13, 4, 7, 6, 1, 8, 11, 10, 5]


In [20]:
rng = np.random.default_rng(seed=123)

In [21]:
rng.integers(0, 100, size=5)  # 5 random integers between 0 and 100

array([ 1, 68, 59,  5, 90])

In [22]:
rng.random(1000)

array([1.84371811e-01, 1.75905901e-01, 8.12094507e-01, 9.23344998e-01,
       2.76574398e-01, 8.19754562e-01, 8.89892693e-01, 5.12970455e-01,
       2.44964601e-01, 8.24241596e-01, 2.13762963e-01, 7.41467052e-01,
       6.29940205e-01, 9.27407259e-01, 2.31908189e-01, 7.99125129e-01,
       5.18165037e-01, 2.31555625e-01, 1.65903993e-01, 4.97788968e-01,
       5.82724641e-01, 1.84337987e-01, 1.48949168e-02, 4.71133229e-01,
       7.28243328e-01, 9.18600492e-01, 6.25534006e-01, 9.17122573e-01,
       8.64690251e-01, 2.18142873e-01, 8.66127431e-01, 7.30751936e-01,
       2.77865290e-01, 7.97043553e-01, 8.65221713e-01, 2.99437896e-01,
       5.27042084e-01, 7.14868066e-02, 5.83238410e-01, 2.37906400e-01,
       7.64963646e-01, 1.73631636e-01, 3.12742256e-01, 1.44744768e-02,
       3.25519216e-02, 4.96701842e-01, 4.68312534e-01, 1.27690323e-01,
       2.57562505e-01, 3.18110929e-03, 3.81067748e-01, 5.75873084e-01,
       4.27298771e-01, 8.35102347e-01, 6.16491251e-01, 2.66083912e-01,
      

In [23]:
rng.uniform(0,1,1000)

array([9.39046881e-01, 2.99072349e-01, 4.60476377e-01, 5.75651076e-02,
       8.53021741e-02, 1.99444561e-01, 6.30163990e-01, 2.72450314e-01,
       9.49816269e-01, 4.16201503e-01, 6.24219978e-01, 5.65506017e-01,
       4.97016101e-01, 3.99685405e-01, 4.46141742e-01, 9.96016783e-01,
       9.20760027e-02, 9.66146235e-01, 2.53428386e-01, 7.98048289e-01,
       2.30934744e-01, 3.91438675e-01, 7.12524762e-01, 9.24495876e-01,
       4.36304104e-01, 6.09645109e-01, 3.47455055e-01, 2.09448681e-01,
       9.40345824e-01, 9.39048542e-01, 9.76034937e-01, 9.78221913e-01,
       9.02928508e-01, 5.60702051e-01, 3.09192067e-01, 3.91578411e-01,
       2.92628804e-01, 3.17626904e-01, 7.66354541e-01, 9.39779224e-01,
       5.69968327e-01, 7.13253015e-01, 2.74080220e-01, 8.95021851e-01,
       5.30589171e-01, 6.62250513e-01, 8.64017361e-01, 3.16234042e-01,
       1.88104862e-01, 5.57143310e-01, 8.17542081e-01, 8.58312274e-01,
       5.01593115e-02, 7.92609803e-01, 2.75257158e-01, 1.06116893e-01,
      

In [24]:
normal_rv = rng.normal(loc=0, scale=4, size=10000)  # 10000 samples from a normal distribution with mean 0 and std dev 1

In [25]:
# check that the sample mean and standard deviation are close to the specified values 

normal_rv.mean()

-0.00030211517930401043

In [26]:
normal_rv.std()

3.988386668060006

In [27]:
rng.integers(0,100) # run this multiple times to observe the random nature of the output

22

In [28]:
import time

# Timing a for loop that generates a random integer in each iteration
start_time = time.time()
steps = 1000000
for _ in range(steps):
    # use a random value
    val = 2*rng.integers(0, 100)
elapsed_no_prealloc = time.time() - start_time

# Timing a for loop that uses preallocated random integers
preallocated = rng.integers(0, 100, size=steps)
start_time = time.time()
for u in preallocated:
    val = 2*u  # use the preallocated value
elapsed_prealloc = time.time() - start_time

print(f"Time without preallocation: {elapsed_no_prealloc:.4f} seconds")
print(f"Time with preallocation: {elapsed_prealloc:.4f} seconds")

Time without preallocation: 0.9014 seconds
Time with preallocation: 0.0658 seconds
